# Generated by Django 3.2.22 on 2023-10-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='idiomas',
            new_name='idioma',
        ),
    ]
