# Generated by Django 3.2.22 on 2023-10-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_rename_idiomas_libro_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='libros',
            field=models.ManyToManyField(related_name='prestamos_libros', through='biblioteca.Prestamo', to='biblioteca.Libro'),
        ),
    ]
