# Generated by Django 3.2.22 on 2023-10-25 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_cliente_libros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='biblioteca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_biblioteca', to='biblioteca.biblioteca'),
        ),
    ]
